# TODO
# general settings
name: 108_MemNet_X2_UW_5886
model_type: SRModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 5886

# dataset and data loader settings
datasets:
  train:
    name: UW
    type: PairedImageDataset
    dataroot_gt: /content/datasets/UW/x2/hr
    dataroot_lq: /content/datasets/UW/x2/lr_2x_l
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X2_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 31
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: USR248_VAL
    type: PairedImageDataset
    dataroot_gt: /content/datasets/benchmark/USR248_VAL/HR
    dataroot_lq: /content/datasets/benchmark/USR248_VAL/LR_bicubicL/X2
    io_backend:
      type: disk

# network structures
network_g:
  type: MemNet


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  # resume_state: experiments/010_RCAN_X2_UW_5886/training_states/80000.state
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-1
    weight_decay: 0.0001
    betas: [0.9, 0.999]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 200000, 300000, 400000]
    gamma: 0.1

  total_iter: 500000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
