# TODO
# general settings
name: 902_TY_X4_UW_T_E5
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 5886

# dataset and data loader settings
datasets:
  train:
    name: UW
    type: PairedImageDataset
    dataroot_gt: datasets/UW/x4/hr
    dataroot_lq: datasets/UW/x4/lr_4x
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 64
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: USR248_VAL
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/USR248_VAL/HR
    dataroot_lq: datasets/benchmark/USR248_VAL/LR_bicubic/X4
    io_backend:
      type: disk

# network structures
network_g:
  type: TY
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_sp_feat: 16
  num_modules: 8
  num_block: 6
  upscale: 4
  img_range: 255.0
  rgb_mean: [0.33024667, 0.41541553, 0.42345934]


# path
path:
  pretrain_network_g: experiments/models/TY_X2_UW_T_E52.pth
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 3e-4
    weight_decay: 0
    betas: [0.99, 0.999]

  scheduler:
    type: MultiStepLR
    milestones: [200000, 350000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
    crop_bd: 4

# validation settings
val:
  val_freq: !!float 2e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
