# general settings
name: 886_FRSN_X2
model_type: SRModel
scale: 2
num_gpu: 1 # set num_gpu: 0 for cpu mode
manual_seed: 5886

# dataset and data loader settings
datasets:
  train:
    name: Flickr2K
    type: PairedImageDataset
    dataroot_gt: datasets/Flickr2K/Flickr2K_HR
    dataroot_lq: datasets/Flickr2K/Flickr2K_LR_bicubic/X2
    filename_tmpl: "{}"
    io_backend:
      type: disk

    gt_size: 64
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: DIV2K_VAL_s
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/DIV2K_VAL_s/HR
    dataroot_lq: datasets/benchmark/DIV2K_VAL_s/LR_bicubic/X2
    io_backend:
      type: disk

# network structures
network_g:
  type: FRSN
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_sp_feat: 16
  num_modules: 8
  num_block: 6
  k_size: 7
  upscale: 2
  img_range: 255.0
  rgb_mean: [0.4488, 0.4371, 0.4040]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 3e-4
    weight_decay: 0
    betas: [0.99, 0.999]

  scheduler:
    type: MultiStepLR
    milestones:
      [
        150000,
        300000,
        450000,
        600000,
        750000,
        900000,
      ]
    gamma: 0.5

  total_iter: 1050000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
    crop_bd: 4

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
